#!/usr/bin/env python3

"""
jobqueue

View job queue information

This script requires:
  - Python 3.5+ (for the subprocess.run command)
  - Slurm (any recent version should work)
"""

import argparse
import subprocess
import sys

# Set up arguments and options ###########################################################

parser = argparse.ArgumentParser(
    prog = "jobqueue",
    formatter_class = argparse.RawDescriptionHelpFormatter,
    description = "View job queue information",
    epilog = """\
examples:

jobqueue
jobqueue --me
jobqueue --all
jobqueue -p gpu
jobqueue -p oneweek,largemem
jobqueue -u ttrojan
jobqueue -u ttrojan,btrojan
jobqueue -p gpu -u ttrojan
jobqueue -a ttrojan_123
jobqueue -n simulation
jobqueue -r class
jobqueue -t pending
jobqueue -w a04-05

notes:

to view completed jobs, run jobhist
to view more job details, run jobinfo <jobid>

support:

https://github.com/uschpc/slurm-tools/issues"""
)
parser.add_argument(
    "-a",
    "--account",
    help = "filter by account (comma-separated list)"
)
parser.add_argument(
    "--all",
    action = "store_true",
    help ="view jobs in all partitions"
)
parser.add_argument(
    "--me",
    action = "store_true",
    help = "view own jobs"
)
parser.add_argument(
    "-n",
    "--name",
    help = "filter by job name (comma-separated list)"
)
parser.add_argument(
    "-w",
    "--nodelist",
    help = "filter by node name (range or comma-separated list)"
)
parser.add_argument(
    "-p",
    "--partition",
    help = "filter by partition (comma-separated list)"
)
parser.add_argument(
    "-r",
    "--reservation",
    help = "filter by reservation name"
)
parser.add_argument(
    "-t",
    "--state",
    help = "filter by job state (comma-separated list)"
)
parser.add_argument(
    "-u",
    "--user",
    help = "filter by user (comma-separated list)"
)
parser.add_argument(
    "-V",
    "--version",
    action = "store_true",
    help = "print version"
)
args = parser.parse_args()

if args.version:
    print("jobqueue 1.3.1")
    sys.exit(0)

# Run squeue command and print results ###################################################

# Specify squeue fields to query and output format
fmt = "%12i %.10u %.12j %.10P %.8T %.11M %.20R"

# Derive squeue command based on given arguments
cmd = ["squeue", "-h", "-o", fmt]
if args.account:
    cmd = cmd + ["-A", args.account]
if args.all:
    cmd = cmd + ["--all"]
if args.me:
    cmd = cmd + ["--me"]
if args.name:
    cmd = cmd + ["-n", args.name]
if args.nodelist:
    cmd = cmd + ["-w", args.nodelist]
if args.partition:
    cmd = cmd + ["-p", args.partition]
if args.reservation:
    cmd = cmd + ["-R", args.reservation]
if args.state:
    cmd = cmd + ["-t", args.state]
if args.user:
    cmd = cmd + ["-u", args.user]

# Run squeue command and print results
print("-----------------------------------------------------------------------------------------")
print("Job ID             User     Job Name  Partition    State     Elapsed     Nodelist(Reason)")
print("------------ ---------- ------------ ---------- -------- ----------- --------------------")
subprocess.run(cmd)
