#!/usr/bin/env bash

# myqueue

# Display job queue information for user

set -e -o pipefail

if [[ -z $1 ]]; then
    user=$USER
else
    user=$1
    # Check if user exists
    if [[ "$(id $user 2>&1)" = *"no such user"* ]]; then
        printf "%s\n" "No such user: $user"
        exit 1
    fi
fi

printf "%s\n" "------------------------------------------------------------------------------"
printf "%s\n" "      Job ID     Job Name  Partition    State     Elapsed     Nodelist(Reason)"
printf "%s\n" "------------ ------------ ---------- -------- ----------- --------------------"
squeue -h -o "%12i %.12j %.10P %.8T %.11M %.20R" -u $user
