#!/usr/bin/env python3

"""
noderes

View available resources on nodes

This script requires:
  - Python 3.7+ (for the subprocess.run options)
  - Slurm 21.08+ (for parsing node state from the scontrol show node output)
  - Slurm configured with:
    - GresTypes=gpu

Notes:
  - Based on output from scontrol
  - Resources include node's CfgTRES (CPUs, memory, and GPUs)
"""

from itertools import groupby
import argparse
import re
import subprocess
import sys

# Set up arguments and options ###########################################################

parser = argparse.ArgumentParser(
    prog = "noderes",
    formatter_class = argparse.RawDescriptionHelpFormatter,
    description = "View available resources on nodes",
    epilog = """\
examples:

noderes
noderes -a
noderes -c
noderes -p gpu
noderes -p main,oneweek
noderes -s idle
noderes -s idle,mixed
noderes -p gpu -s idle
noderes -f
noderes -f -p gpu
noderes -g
noderes -f -g
noderes -f -g -p gpu
noderes -m epyc-7513
noderes -m a100,a40
noderes -fl
noderes -ft ndr200
noderes -z
noderes -z -g

support:

https://github.com/uschpc/slurm-tools/issues"""
)
parser.add_argument(
    "-a",
    "--allocated",
    action = "store_true",
    help = "print allocated resources"
)
parser.add_argument(
    "-c",
    "--configured",
    action = "store_true",
    help = "print configured resources"
)
parser.add_argument(
    "-ft",
    "--feature",
    help = "filter by node feature (comma-separated list)"
)
parser.add_argument(
    "-fl",
    "--feature-list",
    action = "store_true",
    help = "list active node features"
)
parser.add_argument(
    "-f",
    "--free",
    action = "store_true",
    help = "only include nodes with free resources"
)
parser.add_argument(
    "-g",
    "--gpus",
    action = "store_true",
    help = "only include nodes with GPUs"
)
parser.add_argument(
    "-m",
    "--model",
    help = "filter by CPU or GPU model (comma-separated list)"
)
parser.add_argument(
    "-p",
    "--partition",
    help = "filter by partition (comma-separated list)"
)
parser.add_argument(
    "-s",
    "--state",
    help = "filter by node state (comma-separated list)"
)
parser.add_argument(
    "-z",
    "--summary",
    action = "store_true",
    help = "summarize free resources by partition"
)
parser.add_argument(
    "-V",
    "--version",
    action = "store_true",
    help = "print version"
)
args = parser.parse_args()

if args.version:
    print("noderes 1.2.0")
    sys.exit(0)

# Define functions #######################################################################

def memtogib(mem):
    """
    Convert memory value to GiB

    # Arguments
    - mem (str): memory value

    # Returns
    - int: memory value in GiB
    - str: "??" if unit not found
    """
    m = float(mem[:-1])
    if mem.endswith("T"):
        return int(m * 1024)
    if mem.endswith("G"):
        return int(m)
    if mem.endswith("M"):
        return int(m / 1024)
    if mem.endswith("K"):
        return int(m / 1024**2)
    if mem[-1].isdigit():
        return int(mem / 1024**3)
    return "??"

def getnoderes(node):
    """
    Get information about node resources

    # Arguments
    - node (str): single line of node information
                  from "scontrol --oneliner show node" output

    # Returns
    - dict: resource information for node
    """
    # Initialize dict to store results
    d = {
        "nodename":"",
        "partition":"",
        "nodestate":"",
        "nodestateshort":"",
        "cpumodel":"",
        "gpumodel":"",
        "cfgtrescpu":0,
        "cfgtresmem":0,
        "cfgtresgpu":0,
        "alloctrescpu":0,
        "alloctresmem":0,
        "alloctresgpu":0,
        "freecpus":0,
        "freemem":0,
        "freegpus":0
    }

    # Get partition
    partition = re.search(r"Partitions=(\S+)", node)
    # Some nodes may not be assigned partitions yet
    if partition is None:
        d["partition"] = "none"
    else:
        d["partition"] = partition.group(1)

    # Get node name
    d["nodename"] = re.search(r"NodeName=(\S+)", node).group(1)

    # Get node state
    d["nodestate"] = re.search(r"State=(\S+)", node).group(1).lower()
    # Starting with Slurm 21.08, format is base_state+flag
    # For ease of printing, only use base_state with some exceptions
    d["nodestateshort"] = d["nodestate"].split("+", maxsplit = 1)[0]
    if re.search(r"drain", d["nodestate"]):
        # Special type of idle
        d["nodestateshort"] = "drain"
    if re.search(r"maintenance", d["nodestate"]):
        # Can be idle, mixed, or allocated
        d["nodestateshort"] = "maint"
    if re.search(r"reserved", d["nodestate"]):
        # Can be idle, mixed, or allocated
        d["nodestateshort"] = "reserved"

    # Get active node features
    features = re.search(r"ActiveFeatures=(\S+)", node)
    if not features:
        d["features"] = ""
    else:
        d["features"] = features.group(1)

    # Get CPU model
    if not d["features"]:
        d["cpumodel"] = "n/a"
    else:
        cpumodel = re.search(r"((epyc|xeon)[-_a-zA-Z0-9]+)", d["features"])
        if not cpumodel:
            d["cpumodel"] = "n/a"
        else:
            d["cpumodel"] = cpumodel.group(1)

    # Get configured resources for node
    if re.search(r"future|unknown", d["nodestate"]):
        d["cfgtrescpu"] = 0
        d["cfgtresmem"] = 0
        d["cfgtresgpu"] = 0
        d["gpumodel"] = "n/a"
    else:
        cfgtres = re.search(r"CfgTRES=(\S+)", node).group(1)
        # Get CPUs
        cfgtrescpu = re.search(r"cpu=([0-9]+)", cfgtres)
        if not cfgtrescpu:
            d["cfgtrescpu"] = "??"
        else:
            d["cfgtrescpu"] = int(cfgtrescpu.group(1))
        # Get memory (may be in varying units)
        cfgtresmem = re.search(r"mem=([0-9]+.[0-9]+[A-Z]|[0-9]+[A-Z])", cfgtres)
        if not cfgtresmem:
            d["cfgtresmem"] = "??"
        else:
            d["cfgtresmem"] = memtogib(cfgtresmem.group(1))
            if d["cfgtresmem"] != "??":
                # Get memory reserved for Slurm daemons
                memspeclimit = re.search(r"MemSpecLimit=([0-9]+)", node)
                if not memspeclimit:
                    memspeclimit = 0
                else:
                    # Always configured in MiB, convert to GiB
                    memspeclimit = int(float(memspeclimit.group(1)) / 1024)
                # Subtract reserved memory from cfgtresmem
                d["cfgtresmem"] = d["cfgtresmem"] - memspeclimit
        # Get GPUs
        cfgtresgpu = re.search(r"gres/gpu=([0-9]+)", cfgtres)
        if not cfgtresgpu:
            d["cfgtresgpu"] = 0
        else:
            d["cfgtresgpu"] = int(cfgtresgpu.group(1))
        # Get GPU model
        gpumodel = re.search(r"gres/gpu:([a-zA-Z0-9]+)", cfgtres)
        if d["cfgtresgpu"] == 0:
            d["gpumodel"] = "--"
        elif not gpumodel:
            d["gpumodel"] = "n/a"
        else:
            d["gpumodel"] = gpumodel.group(1)

    # Get allocated resources for node and calculate free resources
    if re.search(r"down|error|future|unknown", d["nodestate"]):
        # Set to 0 in order to sum later for args.summary option
        d["alloctrescpu"] = 0
        d["alloctresmem"] = 0
        d["alloctresgpu"] = 0
        d["freecpus"] = 0
        d["freemem"] = 0
        d["freegpus"] = 0
    elif re.search(r"idle", d["nodestate"]):
        d["alloctrescpu"] = 0
        d["alloctresmem"] = 0
        d["alloctresgpu"] = 0
        d["freecpus"] = d["cfgtrescpu"]
        d["freemem"] = d["cfgtresmem"]
        d["freegpus"] = d["cfgtresgpu"]
    else:
        # For node in mixed or allocated state, get allocated values
        # A node is in allocated state only if all CPUs are allocated
        alloctres = re.search(r"AllocTRES=(\S+)", node).group(1)
        # Get CPUs
        alloctrescpu = re.search(r"cpu=([0-9]+)", alloctres)
        if not alloctrescpu:
            d["alloctrescpu"] = "??"
        else:
            d["alloctrescpu"] = int(alloctrescpu.group(1))
        # Get memory (may be in varying units)
        alloctresmem = re.search(r"mem=([0-9]+.[0-9]+[A-Z]|[0-9]+[A-Z])", alloctres)
        if not alloctresmem:
            d["alloctresmem"] = "??"
        else:
            d["alloctresmem"] = memtogib(alloctresmem.group(1))
        # Get GPUs
        alloctresgpu = re.search(r"gres/gpu=([0-9]+)", alloctres)
        if not alloctresgpu:
            d["alloctresgpu"] = 0
        else:
            d["alloctresgpu"] = int(alloctresgpu.group(1))
        # Calculate free CPUs
        if d["cfgtrescpu"] == "??" or d["alloctrescpu"] == "??":
            d["freecpus"] = "??"
        else:
            d["freecpus"] = d["cfgtrescpu"] - d["alloctrescpu"]
        # Calculate free memory
        if d["cfgtresmem"] == "??" or d["alloctresmem"] == "??":
            d["freemem"] = "??"
        else:
            d["freemem"] = d["cfgtresmem"] - d["alloctresmem"]
        # Calculate free GPUs
        if d["cfgtresgpu"] == "??" or d["alloctresgpu"] == "??":
            d["freegpus"] = "??"
        else:
            d["freegpus"] = d["cfgtresgpu"] - d["alloctresgpu"]

    return d

# Get node resource information ##########################################################

# Get scontrol information for all nodes in cluster
cmd = ["scontrol", "--oneliner", "show", "node"]
proc = subprocess.run(cmd, capture_output = True, text = True)
if not proc.stdout:
    print("No nodes found")
    sys.exit(0)
nodelist = proc.stdout.split("\n")[:-1]

# Print active node features
if args.feature_list:
    feats = [re.findall(r"ActiveFeatures=(\S+)", node) for node in nodelist]
    if not feats:
        print("No node features found")
    else:
        # Get sorted list of unique active node features
        feats2 = [feat[0].split(",") for feat in feats]
        feats3 = [allfeat for node in feats2 for allfeat in node]
        ufeats = sorted(list(set(feats3)))
        print("------------------------------")
        print("Active node features")
        print("------------------------------")
        for ufeat in ufeats:
            print(ufeat)
    sys.exit(0)

# Get resource information for each node
reslist = [getnoderes(n) for n in nodelist]

# Filter nodes by node feature
if args.feature:
    nf = args.feature.split(",")
    reslist = [n for n in reslist if any(x in (n["features"]) for x in nf)]

# Only include nodes with free resources
if args.free:
    reslist = [n for n in reslist if n["freecpus"] > 0 and n["freemem"] > 0]

# Only include nodes with GPUs
if args.gpus:
    reslist = [n for n in reslist if n["gpumodel"] != "--"]
    # Only include nodes with accessible GPUs
    if args.free:
        reslist = [n for n in reslist if n["freegpus"] > 0]

# Filter nodes by CPU or GPU model
if args.model:
    fm = args.model.split(",")
    reslist = [n for n in reslist if any(x in (n["cpumodel"] + "," + n["gpumodel"]) for x in fm)]

# Filter nodes by partition
if args.partition:
    fp = args.partition.split(",")
    reslist = [n for n in reslist if any(x in n["partition"] for x in fp)]

# Filter nodes by state
if args.state:
    fs = args.state.split(",")
    reslist = [n for n in reslist if any(x in n["nodestateshort"] for x in fs)]

# Print results ##########################################################################

if not args.summary:
    if not args.configured and not args.allocated:
        # Print free resources for nodes (default)
        print("-------------------------------------------------------------------")
        print("Node      Partition     State         CPU      GPU Free   Free Free")
        print("                                    Model    Model CPUs Memory GPUs")
        print("------ ------------ --------- ----------- -------- ---- ------ ----")
        for n in reslist:
            # For unavailable nodes, replace free values with --
            if re.search(r"down|error|future|unknown", n["nodestate"]):
                n["freecpus"] = "--"
                n["freemem"] = "--"
                n["freegpus"] = "--"
            # For nodes without GPUs, replace GPUs value 0 with --
            if n["gpumodel"] == "--":
                n["freegpus"] = "--"
            print(f"{n['nodename'][:6]:<6}" + " " +
                  f"{n['partition'][:12]:>12}" + " " +
                  f"{n['nodestateshort'][:9]:>9}" + " " +
                  f"{n['cpumodel'][:11]:>11}" + " " +
                  f"{n['gpumodel'][:8]:>8}" + " " +
                  f"{n['freecpus']:>4}" + " " +
                  f"{n['freemem']:>5}" + "G " +
                  f"{n['freegpus']:>4}")
    elif args.configured and not args.allocated:
        # Print configured resources for nodes
        print("-------------------------------------------------------------------")
        print("Node      Partition     State         CPU      GPU  Cfg    Cfg  Cfg")
        print("                                    Model    Model CPUs Memory GPUs")
        print("------ ------------ --------- ----------- -------- ---- ------ ----")
        for n in reslist:
            # For nodes in future or unknown state, replace configured values with --
            if re.search(r"future|unknown", n["nodestate"]):
                n["cfgtrescpu"] = "--"
                n["cfgtresmem"] = "--"
                n["cfgtresgpu"] = "--"
            # For nodes without GPUs, replace GPUs value 0 with --
            if n["gpumodel"] == "--":
                n["cfgtresgpu"] = "--"
            print(f"{n['nodename'][:6]:<6}" + " " +
                  f"{n['partition'][:12]:>12}" + " " +
                  f"{n['nodestateshort'][:9]:>9}" + " " +
                  f"{n['cpumodel'][:11]:>11}" + " " +
                  f"{n['gpumodel'][:8]:>8}" + " " +
                  f"{n['cfgtrescpu']:>4}" + " " +
                  f"{n['cfgtresmem']:>5}" + "G " +
                  f"{n['cfgtresgpu']:>4}")
    else:
        # Print allocated resources for nodes
        print("-------------------------------------------------------------------")
        print("Node      Partition     State         CPU      GPU Alct   Alct Alct")
        print("                                    Model    Model CPUs Memory GPUs")
        print("------ ------------ --------- ----------- -------- ---- ------ ----")
        for n in reslist:
            # For nodes in future or unknown state, replace allocated values with --
            if re.search(r"future|unknown", n["nodestate"]):
                n["alloctrescpu"] = "--"
                n["alloctresmem"] = "--"
                n["alloctresgpu"] = "--"
            # For nodes without GPUs, replace GPUs value 0 with --
            if n["gpumodel"] == "--":
                n["alloctresgpu"] = "--"
            print(f"{n['nodename'][:6]:<6}" + " " +
                  f"{n['partition'][:12]:>12}" + " " +
                  f"{n['nodestateshort'][:9]:>9}" + " " +
                  f"{n['cpumodel'][:11]:>11}" + " " +
                  f"{n['gpumodel'][:8]:>8}" + " " +
                  f"{n['alloctrescpu']:>4}" + " " +
                  f"{n['alloctresmem']:>5}" + "G " +
                  f"{n['alloctresgpu']:>4}")
else:
    if not args.gpus:
        # Summarize information by partition
        print("-----------------------------")
        print("Partition    Free   Free Free")
        print("             CPUs Memory GPUs")
        print("------------ ---- ------ ----")
        # Create sublists by partition
        partlist = []
        sortedreslist = sorted(reslist, key=lambda x: x["partition"])
        for k, v in groupby(sortedreslist, key=lambda x: x["partition"]):
            partlist.append(list(v))
        # Sum and print information by partition
        for p in partlist:
            s = {
                "partition":p[0]["partition"],
                "cfgtresgpu":0,
                "freecpus":0,
                "freemem":0,
                "freegpus":0
            }
            for n in p:
                s["cfgtresgpu"] += n["cfgtresgpu"]
                s["freecpus"] += n["freecpus"]
                s["freemem"] += n["freemem"]
                s["freegpus"] += n["freegpus"]
            # For partitions without GPUs replace 0 with --
            if s["cfgtresgpu"] == 0:
                s["freegpus"] = "--"
            print(f"{s['partition'][:12]:<12}" + " " +
                  f"{s['freecpus']:>4}" + " " +
                  f"{s['freemem']:>5}" + "G " +
                  f"{s['freegpus']:>4}")
    else:
        # Summarize information by partition and GPU model
        print("--------------------------------------")
        print("Partition         GPU Free   Free Free")
        print("                Model CPUs Memory GPUs")
        print("------------ -------- ---- ------ ----")
        # Create sublists by partition and GPU model
        partgpulist = []
        sortedreslist = sorted(reslist, key=lambda x: (x["partition"], x["gpumodel"]))
        for k, v in groupby(sortedreslist, key=lambda x: (x["partition"], x["gpumodel"])):
            partgpulist.append(list(v))
        # Sum and print information by partition and GPU model
        for p in partgpulist:
            s = {
                "partition":p[0]["partition"],
                "gpumodel":p[0]["gpumodel"],
                "freecpus":0,
                "freemem":0,
                "freegpus":0
            }
            for n in p:
                s["freecpus"] += n["freecpus"]
                s["freemem"] += n["freemem"]
                s["freegpus"] += n["freegpus"]
            print(f"{s['partition'][:12]:<12}" + " " +
                  f"{s['gpumodel']:>8}" + " " +
                  f"{s['freecpus']:>4}" + " " +
                  f"{s['freemem']:>5}" + "G " +
                  f"{s['freegpus']:>4}")
