#!/bin/bash

# jobhist

# Print a compact history of user's jobs with basic job information
# Default setting is to print job history for past 7 days
# Based on output from sacct

if [ -z "$1" ]; then
    days=7;
else
    days=$1;
    if ! [ $1 -eq $1 2> /dev/null ] || [ "$1" -lt 1 ]; then
        echo "Error: The argument should be a positive integer indicating days to list in history"
        exit 1
    fi;
fi;
seconds=$(($days * 24 * 60 * 60));
now=$(date +%s);
minusdays=$((now - $seconds));
startdate=$(date --date=@$minusdays +'%m/%d');

if [ -z  "$2" ]; then
    user=$USER
else
    user=$2
fi

FORMAT=start%10,jobid%-13,jobname%12,partition,state,elapsed,nnodes%5,ncpus%4,reqmem%7

echo "-----------------------------------------------------------------------------------------"
echo " Startdate        Job ID     Job Name  Partition      State    Elapsed Nodes CPUs  Memory"
echo "---------- ------------- ------------ ---------- ---------- ---------- ----- ---- -------"
sacct -u $user -S $startdate -n -o $FORMAT | egrep -v '(       batch|      extern|\.in|[0-9]{4}\.[0-9])';
