#!/bin/bash

# myqueue

# Print job queue information for user

if [ -z  "$1" ]; then
    user=$USER
else
    user=$1
fi

echo "------------------------------------------------------------------------------"
echo "      Job ID     Job Name  Partition    State     Elapsed     Nodelist(Reason)"
echo "------------ ------------ ---------- -------- ----------- --------------------"
squeue -u $user -h -o "%12i %.12j %.10P %.8T %.11M %.20R"
